### ISSUE TITLE
Inconsistent failure to reach last frame when frame interpolation is enabled

### ISSUE THREAD

**Issue by theashraf** [LottieFiles/dotlottie-rs#116]
inconsistent failure For this test case, `use_frame_interpolation` is enabled by default. The animation loop should terminate when `is_complete` is true, but this never occurs. Instead, `current_frame` becomes stuck at `current_frame = last_frame - 0.0000xx`. For example, if there are a total of 41 frames, `current_frame` remains stuck at frame 40.9999xx, although `request_frame` correctly returns the last frame as 41.

The issue might potentially lie within the `set_frame` function. 🤔

```rs
#[test]
fn test_autoplay() {
    let player = DotLottiePlayer::new(Config {
        autoplay: true,
        ..create_default_config()
    });

    assert!(player.load_animation_path("tests/assets/test.json", WIDTH, HEIGHT));
    assert!(player.is_playing());
    assert!(!player.is_paused());
    assert!(!player.is_stopped());
    assert_eq!(player.is_complete(), false);
    assert_eq!(player.current_frame(), 0.0);

    let mut rendered_frames: Vec<f32> = vec![];

    loop {
        let next_frame = player.request_frame();

        if player.set_frame(next_frame) {
            if player.render() {
                let current_frame = player.current_frame();
                rendered_frames.push(current_frame);
            }
        }

        if player.is_complete() { // expected to terminate the render loop 
            break;
        }
    }

    assert!(!rendered_frames.is_empty());
    println!("Rendered frames: {:?}", rendered_frames.len());
}
```

**Comment by theashraf** [comment]
Related to https://github.com/thorvg/thorvg/issues/2147

**Comment by theashraf** [comment]
Given that tvg_set_frame [ignores the frame value if the difference is less than 0.001](https://github.com/thorvg/thorvg/issues/2147#issuecomment-2044254579), we can consider the animation to be completed if the difference between current_frame and end_frame is less than 0.001

Also as an optimization, if `request_frame()` is expected to return a new frame number that differs from `current_frame` by less than 0.001, we can return the same `current_frame` value instead. This is because such a minor difference will be ignored by `tvg_set_frame` anyway

**Comment by hermet** [comment]
@theashraf Hello, this might be helpful for your consideration: https://github.com/thorvg/thorvg/pull/2158. It rounds up values less than 0.001.
